USE QLSVNhom;
GO

IF OBJECT_ID(N'dbo.BANGDIEM', N'U') IS NOT NULL DROP TABLE dbo.BANGDIEM;
IF OBJECT_ID(N'dbo.SINHVIEN', N'U') IS NOT NULL DROP TABLE dbo.SINHVIEN;
IF OBJECT_ID(N'dbo.HOCPHAN', N'U') IS NOT NULL DROP TABLE dbo.HOCPHAN;
IF OBJECT_ID(N'dbo.LOP', N'U') IS NOT NULL DROP TABLE dbo.LOP;
IF OBJECT_ID(N'dbo.NHANVIEN', N'U') IS NOT NULL DROP TABLE dbo.NHANVIEN;
GO

/*
Lab 04 yêu cầu:
- Mã hóa dữ liệu ở client trước khi lưu xuống CSDL.
- Giải mã dữ liệu ở client sau khi truy vấn.
- Public key được lưu trong DB.
- Private key KHÔNG lưu trong DB.

Thiết kế ở đây:
- MATKHAU lưu dạng VARBINARY(64) = SHA-512 raw bytes.
- LUONG / DIEMTHI lưu dạng VARCHAR(500) = ciphertext RSA-2048 mã hóa ở client, encode Base64.
- PUBKEY lưu dạng VARCHAR(500) = public key RSA-2048 export ở client, encode Base64 (DER/SPKI).
*/

CREATE TABLE dbo.NHANVIEN
(
    MANV     VARCHAR(20)    NOT NULL,
    HOTEN    NVARCHAR(100)  NOT NULL,
    EMAIL    VARCHAR(100)   NULL,
    LUONG    VARCHAR(500)   NOT NULL,
    TENDN    NVARCHAR(100)  NOT NULL,
    MATKHAU  VARBINARY(64)  NOT NULL,
    PUBKEY   VARCHAR(500)   NOT NULL,

    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
    CONSTRAINT UQ_NHANVIEN_TENDN UNIQUE (TENDN),
    CONSTRAINT UQ_NHANVIEN_PUBKEY UNIQUE (PUBKEY)
);
GO

CREATE TABLE dbo.LOP
(
    MALOP    VARCHAR(20)    NOT NULL,
    TENLOP   NVARCHAR(100)  NOT NULL,
    MANV     VARCHAR(20)    NULL,

    CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
    CONSTRAINT FK_LOP_NHANVIEN
        FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
);
GO

CREATE TABLE dbo.HOCPHAN
(
    MAHP     VARCHAR(20)    NOT NULL,
    TENHP    NVARCHAR(100)  NOT NULL,
    SOTC     INT            NULL,

    CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP),
    CONSTRAINT CK_HOCPHAN_SOTC CHECK (SOTC IS NULL OR SOTC > 0)
);
GO

CREATE TABLE dbo.SINHVIEN
(
    MASV      VARCHAR(20)     NOT NULL,
    HOTEN     NVARCHAR(100)   NOT NULL,
    NGAYSINH  DATETIME        NULL,
    DIACHI    NVARCHAR(200)   NULL,
    MALOP     VARCHAR(20)     NULL,
    TENDN     NVARCHAR(100)   NOT NULL,
    MATKHAU   VARBINARY(64)   NOT NULL,

    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
    CONSTRAINT UQ_SINHVIEN_TENDN UNIQUE (TENDN),
    CONSTRAINT FK_SINHVIEN_LOP
        FOREIGN KEY (MALOP) REFERENCES dbo.LOP(MALOP)
);
GO

CREATE TABLE dbo.BANGDIEM
(
    MASV      VARCHAR(20)    NOT NULL,
    MAHP      VARCHAR(20)    NOT NULL,
    DIEMTHI   VARCHAR(500)   NOT NULL,

    CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV, MAHP),
    CONSTRAINT FK_BANGDIEM_SINHVIEN
        FOREIGN KEY (MASV) REFERENCES dbo.SINHVIEN(MASV),
    CONSTRAINT FK_BANGDIEM_HOCPHAN
        FOREIGN KEY (MAHP) REFERENCES dbo.HOCPHAN(MAHP)
);
GO
